### ISSUE TITLE
Server system locale is limited

### ISSUE THREAD

**Issue by Sengchheang** [visay/DockerTYPO3#4]
in LocalConfiguration.php, my setting is 

`'systemLocale' => 'sv_SE.UTF-8',`

<img width="1221" alt="screen shot 2016-09-28 at 10 17 01 pm" src="https://cloud.githubusercontent.com/assets/635758/18920155/c23619ba-85ca-11e6-8ea8-473de0d30aae.png">

But it is fine when changing 'en_US.UTF-8'

**Comment by visay** [comment]
@Sengchheang  fixed with this commit https://github.com/visay/DockerTYPO3/commit/bc0f2b18bffd59e70edde93433c45d5234ea59d6 and released a new version 2.1.1

Added some popular locales as in the commit changes.

Make sure your composer pull version 2.1.1 and it should be fixed. Test and close this ticket if it works, otherwise let me know.
